<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="92656" started-at="2017-11-28T21:46:17Z" finished-at="2017-11-28T21:47:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="92656" started-at="2017-11-28T21:46:17Z" finished-at="2017-11-28T21:47:50Z">
      <class name="PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp@56ac3a89]" name="beforeMethod" is-config="true" duration-ms="51171" started-at="2017-11-28T15:46:17Z" finished-at="2017-11-28T15:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="Test()[pri:0, instance:PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp@56ac3a89]" name="Test" duration-ms="23230" started-at="2017-11-28T15:47:09Z" finished-at="2017-11-28T15:47:32Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.Tools.findName(Tools.java:150)
	at PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp.start(FoxApp.java:208)
	at PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp.Test(FoxApp.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp@56ac3a89]" name="afterMethod" is-config="true" duration-ms="18212" started-at="2017-11-28T15:47:32Z" finished-at="2017-11-28T15:47:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- PRUEBAFoxAppAndroid.PRUEBAFoxAppAndroid.FoxApp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
